
tasks:
  - init: yarn install

# List the ports to expose. Learn more https://www.gitpod.io/docs/config-ports/
ports:
  - port: 8000
    onOpen: ignore

vscode:
  extensions:
    - eamodio.gitlens
    - github.vscode-pull-request-github
    - dbaeumer.vscode-eslint
    - beardedbear.beardedtheme
    - pkief.material-icon-theme
    - bradlc.vscode-tailwindcss
    - syler.sass-indented
